INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (1, 'Ravai 1kg', 'Pillsbury', 2, 99, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (2, 'Nalennai 1L', 'Idhayam', 2, 520, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (3, 'Nalennai 1L', 'Safola', 2, 248, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (4, 'Aval 500g', 'Khar', 2, 65, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (5, 'Noodles 420g', 'Maggie', 2, 115, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (6, 'Semiya 450g', 'Anil', 2, 60, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (7, 'Figs 300g', 'Anjeer', 1, 195, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (8, 'Ragi Semiya 180g', 'Anil', 4, 66, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (9, 'Tomato Ketchup', 'Heinz', 1, 48, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (10, 'Tea 500g', 'Chakra Gold', 1, 200, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (11, 'Washing bar 95g', 'Surf Excel', 4, 38, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (12, 'Washing powder', 'Rin', 1, 80, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (13, 'Coffee 200g', 'Bru', 1, 287, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (14, 'Washing liquid', 'Surf Excel', 2, 452, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (15, 'Balm', 'Axe', 1, 263, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (16, 'Appalam', 'Bindhu', 2, 119, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (17, 'Shampoo', 'Sunsilk', 1, 188, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (18, 'Toothpaste', 'Pepsodent', 1, 94, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (19, 'Toilet Flush 500ml', 'Harpic', 4, 260, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (20, 'Insect Killer 200ml', 'Hit', 2, 162, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (21, 'Coconut Oil 250ml', 'Parachute', 4, 330, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (22, 'Shower gel', 'Fiama de wills', 1, 144, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (23, 'Glass Cleaner', 'Colin', 1, 70, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (24, 'Toilet Floor 500ml', 'Lizol', 4, 156, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (25, 'Hand Sanitizer', 'Himalaya', 1, 47, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (26, 'Bath Soap', 'Hamam', 6, 144, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (27, 'Freshner', 'Glad', 1, 88, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (28, 'Body Odour', 'Yardley', 1, 173, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (29, 'Scrubber', 'SB', 1, 75, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (30, 'Screen Cleaner', 'SC', 1, 262, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (31, 'Dish wash Liquid', 'Vim', 1, 169, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (32, 'Salt 1kg', 'Tata', 2, 33, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (33, 'Pepper powder 50g', 'Everest', 2, 79, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (34, 'Vendhayam 200g', 'Ponnu', 2, 29, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (35, 'Corn flour 100g', 'KG', 1, 22, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (36, 'Garam Masala 100g', 'Everest', 1, 59, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (37, 'Mookadalai 500g', 'Ponnu', 1, 38, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (38, 'Pachai payir', 'Ponnu', 1, 110, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (39, 'Chilli Powder 500g', 'Sakthi', 1, 83, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (40, 'Perungayam Katti 50g', 'LG', 2, 82, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (41, 'Salt Lite 1kg', 'Tata', 1, 26, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (42, 'Malli Thool 500g', 'Aachi', 1, 81, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (43, 'ManjalThool 500g', 'Aachi', 1, 73, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (44, 'Seeragam Powder 50g', 'Everest', 2, 43, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (45, 'Milagu 200g', 'Ponnu', 2, 420, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (46, 'Seeragam 200g', 'Ponnu', 2, 92, null);
INSERT INTO test.product_details (id, name, brand, quantity, price, rate) VALUES (47, 'Perungayam 100g', 'LG', 1, 85, null);